name: Publish release Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: echo tag_name
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: echo "$TAG"
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Push image to hubs
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            f1nnm/docker-monitor:release-${{ github.event.release.tag_name }}
            f1nnm/docker-monitor:latest
            ghcr.io/f1nnm/docker-monitor:release-${{ github.event.release.tag_name }}
            ghcr.io/f1nnm/docker-monitor:latest